* Basics of Programming in C++
*Welcome to my humble programming with C++ tutorials.*

In these tutorials, we’ll learn programming together using the book: [[https://www.stroustrup.com/programming.html][Programming -- Principles and Practice Using C++ (3rd Edition)]].

The code in this repository is a supplement to my [[https://www.youtube.com/watch?v=hUb6sFqVzE0&list=PLAHKaJGVF3tq9nAQNCSbjQFZe8PULjxUI][Youtube tutorials]].

Each directory in this repo corresponds to a YouTube video and contains the =.org= file featured in that video, which includes the full tutorial.

You’ll also find a few subdirectories with solutions to drills and exercises, as well as images used in the =.org= files.

#+begin_quote
⚠️ **Warning:** *The solutions are meant only for comparison with your own work.*
Please don’t use them as a shortcut to the answers for drills, exercises, etc.
If you want to get the maximum benefit from the course, try to solve everything on your own first.
Then, use the solutions only to check whether your answers match the expected standard.
#+end_quote

If you run into any issues, please don’t hesitate to open a pull request.
That’s it—enjoy! 😊
