* Basics of Programming in C++
*Welcome to my humble programming with C++ tutorials.*

In these tutorials, we’ll learn programming together using the book: [[https://www.stroustrup.com/programming.html][Programming -- Principles and Practice Using C++ (3rd Edition)]].

The code in this repository is a supplement to my [[https://www.youtube.com/watch?v=hUb6sFqVzE0&list=PLAHKaJGVF3tq9nAQNCSbjQFZe8PULjxUI][Youtube tutorials]].

Each directory in this repo corresponds to a YouTube video and contains the =.org= file featured in that video, which includes the full tutorial.

You’ll also find a few subdirectories with solutions to drills and exercises, as well as images used in the =.org= files.

#+begin_quote
⚠️ **Warning:** *The solutions are meant only for comparison with your own work.*
Please don’t use them as a shortcut to the answers for drills, exercises, etc.
If you want to get the maximum benefit from the course, try to solve everything on your own first.
Then, use the solutions only to check whether your answers match mine.
#+end_quote

If you run into any issues, please don’t hesitate to open a an issue or a PR.
That’s it—enjoy! 😊

** Prerequisites
This course assumes that you already have a working setup consisting of:
1. *A text editor* – This can be VS Code, Visual Studio, Notepad++, Sublime Text, Vim, etc.
2. *C++ compiler* – Such as GCC, Clang, MSVC, etc.

If you don’t already have these tools installed, please search online for [[https://www.youtube.com/watch?v=DMWD7wfhgNY&t=135s][how to set up a C++ programming environment.]]
The linked video is a good start, it uses GCC compiler with Visual Studio Code text editor, also there are plenty of tutorials on YouTube that cover this topic in detail,
choose the setup you like :).
